# Site settings
title: Clean Code
header-img: img/home-bg.jpg
email: tushar.bhushan@yahoo.com
description: "Tales of the master control program"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: tushdante
github_username:  tushdante
facebook_username: tusharbhushan
linkedin_username: tbhushan

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

#Gems
gems: [yaml, oauth, json]
