# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: tushar.bhushan@yahoo.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: tushdante
github_username:  tushdante
facebook_username:  IronSummitMedia
linkedin_username: tbhushan

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

#Gems
gems: [yaml, oauth, json]
